import React,{useState} from 'react';
import {View,Text,Pressable,TextInput,StyleSheet} from 'react-native';
import {api} from './api';
type Status={status:string;source_count?:number;partition_counts?:Record<string,number>;test_accuracy?:number};
type Prediction={status:string;suggestions:{target:string;model_score:number}[];note?:string};
export function KnowledgeExplorer(){
 const[open,setOpen]=useState(false),[status,setStatus]=useState<Status|null>(null),[name,setName]=useState(''),[prediction,setPrediction]=useState<Prediction|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function show(){if(busy)return;if(open){setOpen(false);return;}setOpen(true);setBusy(true);setError('');try{setStatus(await api('/knowledge/status'));}catch(e){setError(e instanceof Error?e.message:'Model status unavailable.');}finally{setBusy(false);}}
 async function classify(){if(busy||name.trim().length<2)return;setBusy(true);setPrediction(null);setError('');try{setPrediction(await api('/knowledge/classify?name='+encodeURIComponent(name.trim())));}catch(e){setError(e instanceof Error?e.message:'Could not classify that name.');}finally{setBusy(false);}}
 return <View style={s.box}><Pressable accessibilityRole="button" accessibilityState={{expanded:open,disabled:busy}} disabled={busy} onPress={()=>void show()} style={s.button}><Text style={s.link}>{open?'Hide neural model details':'Explore the trained neural model'}</Text></Pressable>{open&&<>{status?.status==='trained_experimental'?<><Text style={s.text}>{status.source_count} source exercises · {status.partition_counts?.train} used to train the network</Text><Text style={s.muted}>Held-out target-label accuracy: {((status.test_accuracy??0)*100).toFixed(1)}%. This measures agreement with the source labels, not safety or anatomical understanding. Some categories perform poorly.</Text><Text style={s.text}>Try an exercise name</Text><TextInput accessibilityLabel="Exercise name for experimental category prediction" maxLength={200} value={name} onChangeText={v=>{setName(v);setPrediction(null);}} style={s.input}/><Pressable accessibilityRole="button" accessibilityState={{disabled:busy||name.trim().length<2}} disabled={busy||name.trim().length<2} onPress={()=>void classify()} style={s.button}><Text style={s.link}>{busy?'Checking…':'Suggest a target category'}</Text></Pressable></>:<Text style={s.muted}>{busy?'Loading model status…':'Neural model unavailable. Catalog references still work.'}</Text>}{prediction&&<><Text style={s.text}>{prediction.status==='experimental_suggestion'?'Experimental suggestions':'Uncertain — choose the exact exercise in Library'}</Text>{prediction.status==='experimental_suggestion'&&prediction.suggestions.map(p=><Text key={p.target} style={s.text}>{p.target} · model score {p.model_score.toFixed(2)}</Text>)}<Text style={s.muted}>{prediction.note??'No prediction is available.'} This does not change your workout.</Text></>}{!!error&&<Text accessibilityRole="alert" style={s.text}>{error}</Text>}</>}</View>;
}
const s=StyleSheet.create({box:{gap:12},button:{minHeight:48,padding:12,borderRadius:12,borderWidth:1,borderColor:'#35473b',justifyContent:'center'},link:{fontSize:16,color:'#d1f599'},text:{fontSize:16,lineHeight:25,color:'#f1f5ee'},muted:{fontSize:14,lineHeight:22,color:'#b5c3b9'},input:{minHeight:50,padding:12,borderRadius:12,borderWidth:1,borderColor:'#35473b',fontSize:16,color:'#f1f5ee'}});
