import React,{useEffect,useState} from 'react';
import {StyleSheet,Text,View,ScrollView,Pressable,TextInput,Switch,Alert} from 'react-native';
import {SafeAreaProvider,SafeAreaView} from 'react-native-safe-area-context';
import {StatusBar} from 'expo-status-bar';
import {api,load,sync,ApiError} from './src/api';
import * as store from './src/storage';
import {ExerciseTutorial} from './src/ExerciseTutorial';
const tabs=['Today','Library','Progress','Coach','Settings'] as const;
const colors={bg:'#101915',card:'#1c2a23',lime:'#d1f599',text:'#f1f5ee',muted:'#b5c3b9',line:'#35473b'};
function Button({label,onPress,secondary=false}:{label:string;onPress:()=>void;secondary?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={[s.button,secondary&&s.secondary]}><Text style={[s.buttonText,secondary&&{color:colors.text}]}>{label}</Text></Pressable>;}
function Field({label,value,onChange,secure=false,numeric=false}:{label:string;value:string;onChange:(v:string)=>void;secure?:boolean;numeric?:boolean}){return <View><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} secureTextEntry={secure} keyboardType={numeric?'numeric':'default'} autoCapitalize="none" style={s.input}/></View>;}
export default function App(){
 const [session,setSession]=useState(false),[ready,setReady]=useState(false),[tab,setTab]=useState<typeof tabs[number]>('Today');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[profile,setProfile]=useState<any>(null);
 const [goals,setGoals]=useState({strength:'40',hypertrophy:'30',cardio:'20',mobility:'10'}),[equipment,setEquipment]=useState('body weight'),[minutes,setMinutes]=useState('40');
 const [sleep,setSleep]=useState('7'),[energy,setEnergy]=useState('3'),[soreness,setSoreness]=useState('1'),[stress,setStress]=useState('2'),[pain,setPain]=useState(false);
 const [workout,setWorkout]=useState<any>(null),[query,setQuery]=useState(''),[exercises,setExercises]=useState<any[]>([]),[progress,setProgress]=useState<any>(null);
 const [message,setMessage]=useState(''),[reply,setReply]=useState(''),[status,setStatus]=useState(''),[advanced,setAdvanced]=useState(false),[keys,setKeys]=useState<any[]>([]),[newKey,setNewKey]=useState('');
 const [outbox,setOutbox]=useState<any[]>([]),[busy,setBusy]=useState(false),[nutrition,setNutrition]=useState<any>(null),[weight,setWeight]=useState('74'),[maintenance,setMaintenance]=useState('2500');
 const [logged,setLogged]=useState<Record<string,boolean>>({});
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);try{await fn();}catch(e){setStatus(e instanceof Error?e.message:'Something went wrong. Try again.');}finally{setBusy(false);}}
 useEffect(()=>{void (async()=>{try{await store.init();const t=await store.token();setSession(!!t);if(t){const p=await load('/profile');setProfile(p.data);const w=await store.cached<any>('today');setWorkout(w);setLogged(await store.cached<Record<string,boolean>>('logged')||{});setOutbox(await store.pending());if(p.offline)setStatus('Offline • showing saved information');}}catch(e){setStatus(e instanceof Error?e.message:'Setup needed');}finally{setReady(true);}})();},[]);
 async function signIn(register:boolean){await store.clear();const r=await api('/auth/'+(register?'register':'login'),'POST',{email,password});await store.setToken(r.key);setSession(true);setPassword('');setStatus('Signed in');if(!register){const p=await api('/profile');setProfile(p);}}
 async function saveProfile(){const p={display_name:name,adult:true,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,experience:0,goals:Object.fromEntries(Object.entries(goals).map(([k,v])=>[k,Number(v)])),equipment:equipment.split(',').map(x=>x.trim()).filter(Boolean),minutes:Number(minutes),days:[0,2,4],nutrition:false,gamification:true};await api('/profile','PUT',p);await store.cache('/profile',p);setProfile(p);setStatus('Profile saved');}
 async function today(){await api('/readiness','POST',{sleep_hours:Number(sleep),energy:Number(energy),soreness:Number(soreness),stress:Number(stress),pain,red_flag:false});if(pain){setWorkout(null);await store.cache('today',null);setStatus('Workout paused. Clarify pain before continuing.');return;}const w=await api('/workouts/today','POST');setWorkout(w);await store.cache('today',w);setStatus('Your plan is ready');}
 async function record(item:any,n:number,reps:string,load:string,rpe:string,hasPain:boolean,skipped:boolean){if(!workout) return;if(![Number(reps),Number(load),Number(rpe)].every(Number.isFinite)||!Number.isInteger(Number(reps))||Number(reps)<0||Number(reps)>200||Number(load)<0||Number(load)>600||Number(rpe)<1||Number(rpe)>10)throw new Error('Enter valid reps (0–200), load (0–600 kg), and RPE (1–10).');await store.queue({workout_id:workout.id,exercise_id:item.exercise_id,set_number:n,reps:Number(reps),load_kg:Number(load),rpe:Number(rpe),pain:hasPain,skipped});const next={...logged,[`${workout.id}:${item.exercise_id}:${n}`]:true};setLogged(next);await store.cache('logged',next);if(hasPain){workout.status='paused';setWorkout({...workout});await store.cache('today',workout);}setOutbox(await store.pending());setStatus(hasPain?'Pain recorded. Stop this workout.':'Set saved on this device');try{await sync();}catch{setStatus('Saved offline. Sync when connected.');}setOutbox(await store.pending());}
 async function selectTab(t:typeof tabs[number]){setTab(t);await run(async()=>{if(t==='Progress')setProgress((await load('/progress')).data);if(t==='Library')setExercises((await load<any[]>('/exercises?q='+encodeURIComponent(query))).data);if(t==='Settings')setKeys(await api('/api-keys'));});}
 if(!ready)return <SafeAreaProvider><SafeAreaView style={s.root}><Text style={s.text}>Opening your training space…</Text></SafeAreaView></SafeAreaProvider>;
 return <SafeAreaProvider><SafeAreaView style={s.root}><StatusBar style="light"/><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><View style={s.brand}><Text style={s.logo}>A / F</Text><Text style={s.eyebrow}>ADAPTIVE FITNESS OS</Text></View>
 {!!status&&<Text accessibilityLiveRegion="polite" style={s.status}>{busy?'Working… ':''}{status}</Text>}
 {!session?<><Text style={s.title}>Built around\nyour next step.</Text><Text style={s.muted}>Training that respects your goals and recovery.</Text><Field label="Email" value={email} onChange={setEmail}/><Field label="Password · at least 12 characters" value={password} onChange={setPassword} secure/><Button label="Sign in" onPress={()=>void run(()=>signIn(false))}/><Button secondary label="Create account" onPress={()=>void run(()=>signIn(true))}/></>:!profile?<><Text style={s.title}>Make it yours.</Text><Text style={s.muted}>Quick setup · adults 18+ · beginner plan. Guided assessments and data imports are planned integrations.</Text><Field label="Your name" value={name} onChange={setName}/>{Object.entries(goals).map(([k,v])=><Field key={k} label={k+' priority %'} value={v} numeric onChange={x=>setGoals({...goals,[k]:x})}/>)}<Text style={s.muted}>Total: {Object.values(goals).reduce((a,v)=>a+Number(v),0)}% · must equal 100%</Text><Field label="Equipment, comma separated" value={equipment} onChange={setEquipment}/><Field label="Workout minutes" value={minutes} onChange={setMinutes} numeric/><Text style={s.muted}>Training days: Monday, Wednesday, Friday. Change schedule through the profile API in this development build.</Text><Button label="I am 18 or older · Save profile" onPress={()=>void run(saveProfile)}/></>:<>
 <View style={s.tabs}>{tabs.map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:tab===t}} onPress={()=>void selectTab(t)} style={[s.tab,tab===t&&s.activeTab]}><Text style={[s.tabText,tab===t&&{color:colors.bg}]}>{t}</Text></Pressable>)}</View>
 {tab==='Today'&&<><Text style={s.eyebrow}>YOUR DAILY CHECK-IN</Text><Text style={s.title}>Move forward,\n{profile.display_name}.</Text><Text style={s.muted}>A good session starts with how you feel.</Text><View style={s.card}><Text style={s.heading}>How are you arriving?</Text><Field label="Sleep · hours" value={sleep} onChange={setSleep} numeric/><Field label="Energy · 1 to 5" value={energy} onChange={setEnergy} numeric/><Field label="Soreness · 0 to 5" value={soreness} onChange={setSoreness} numeric/><Field label="Stress · 0 to 5" value={stress} onChange={setStress} numeric/><View style={s.row}><Text style={s.text}>Pain during movement?</Text><Switch accessibilityLabel="Pain during movement" value={pain} onValueChange={setPain}/></View><Button label="Check readiness & plan" onPress={()=>void run(today)}/></View>
 {workout&&<View style={s.card}><Text style={s.eyebrow}>{workout.kind==='recovery'?'RECOVERY COUNTS':'YOUR SESSION'}</Text><Text style={s.heading}>{workout.minutes} minutes · readiness {workout.readiness}</Text><Text style={s.muted}>{workout.status==='paused'?'Paused — stop training and clarify pain.':'Saved session • verify readiness before training.'}</Text>{workout.preparation.map((x:string,i:number)=><Text key={i} style={s.text}>• {x}</Text>)}{workout.items.map((item:any)=><View key={item.exercise_id} style={s.exercise}><Text style={s.heading}>{item.name}</Text><Text style={s.muted}>{item.sets} sets × {item.reps} reps · RPE {item.rpe} · rest {item.rest_seconds}s</Text><ExerciseTutorial exerciseId={item.exercise_id} name={item.name}/>{item.instructions.map((x:string,i:number)=><Text key={i} style={s.text}>{i+1}. {x}</Text>)}{advanced&&<Text style={s.muted}>{JSON.stringify(item.reasoning)}{'\n'}{item.adjustment.reason}</Text>}{workout.status==='planned'&&Array.from({length:item.sets},(_,i)=><SetEntry key={i} number={i+1} done={!!logged[`${workout.id}:${item.exercise_id}:${i+1}`]} item={item} save={(r,l,e,p,sk)=>void run(()=>record(item,i+1,r,l,e,p,sk))}/>)}<Button secondary label="Machine occupied · find replacement" onPress={()=>void run(async()=>{const w=await api('/workouts/'+workout.id+'/substitute','POST',{exercise_id:item.exercise_id,reason:'occupied'});setWorkout({...w,status:'planned'});await store.cache('today',{...w,status:'planned'});})}/></View>)}{workout.cooldown.map((x:string,i:number)=><Text key={i} style={s.text}>• {x}</Text>)}<Button label="Finish session" onPress={()=>void run(async()=>{await sync();if((await store.pending()).length)throw new Error('Resolve pending logs before completing.');await api('/workouts/'+workout.id+'/complete','POST');const w={...workout,status:'completed'};setWorkout(w);await store.cache('today',w);setStatus('Session complete. Recovery is part of progress.');})}/></View>}
 <View style={s.row}><Text style={s.text}>Show programming details</Text><Switch accessibilityLabel="Advanced programming details" value={advanced} onValueChange={setAdvanced}/></View><Text style={s.muted}>{outbox.length} pending logs</Text><Button secondary label="Sync saved sets" onPress={()=>void run(async()=>{await sync();setOutbox(await store.pending());setStatus('Synchronization checked');})}/>{outbox.filter(x=>x.error).map(x=><Text key={x.id} style={s.status}>Needs review: {x.error}</Text>)}</>}
 {tab==='Library'&&<><Text style={s.title}>Know the movement.</Text><Field label="Search exercises" value={query} onChange={setQuery}/><Button label="Search" onPress={()=>void run(async()=>setExercises((await load<any[]>('/exercises?q='+encodeURIComponent(query))).data))}/>{exercises.map(e=><View key={e.id} style={s.card}><Text style={s.heading}>{e.name}</Text><Text style={s.eyebrow}>{e.equipment}</Text><ExerciseTutorial exerciseId={e.id} name={e.name}/>{e.instructions.map((x:string,i:number)=><Text key={i} style={s.text}>{i+1}. {x}</Text>)}</View>)}</>}
 {tab==='Progress'&&<><Text style={s.title}>Consistency,\nmade visible.</Text>{progress&&<View style={s.card}><Text style={s.heroNumber}>{progress.xp} XP</Text><Text style={s.heading}>Level {progress.level}</Text><Text style={s.muted}>Rest days never remove progress.</Text>{Object.entries(progress.exercise_history).map(([k,v]:any)=><Text key={k} style={s.text}>{k} · {v.sessions.length} recorded sessions</Text>)}</View>}</>}
 {tab==='Coach'&&<><Text style={s.title}>Understand\nyour training.</Text><Text style={s.muted}>Rule-based helper · conversational model not connected.</Text><Field label="Ask about your plan" value={message} onChange={setMessage}/><Button label="Ask coach" onPress={()=>void run(async()=>setReply((await api('/coach','POST',{message})).reply))}/>{!!reply&&<View style={s.card}><Text style={s.text}>{reply}</Text></View>}</>}
 {tab==='Settings'&&<><Text style={s.title}>Your controls.</Text><View style={s.card}><Text style={s.heading}>Developer API access</Text><Text style={s.muted}>Keys access your fitness backend. They do not provide credits or access to external AI providers.</Text><Button label="Create read-only key · 30 days" onPress={()=>void run(async()=>{const k=await api('/api-keys','POST',{name:'Personal integration',scopes:['read'],expires_days:30});setNewKey(k.key);setKeys(await api('/api-keys'));})}/>{!!newKey&&<><Text style={s.muted}>Copy now. This secret is only shown once.</Text><Text selectable style={s.text}>{newKey}</Text><Button secondary label="Hide key" onPress={()=>setNewKey('')}/></>}{keys.map(k=><View key={k.id}><Text style={s.text}>{k.name} · {k.revoked?'revoked':'active'}</Text>{!k.revoked&&<Button secondary label="Revoke key" onPress={()=>void run(async()=>{await api('/api-keys/'+k.id,'DELETE');setKeys(await api('/api-keys'));})}/>}</View>)}</View>
 <View style={s.card}><Text style={s.heading}>Optional nutrition</Text><Text style={s.muted}>Approximate targets for generally healthy adults. Nutrition is off until enabled.</Text><Button secondary label="Enable nutrition" onPress={()=>void run(async()=>{const p={...profile,nutrition:true};await api('/profile','PUT',p);setProfile(p);await store.cache('/profile',p);})}/><Field label="Weight · kg" value={weight} onChange={setWeight} numeric/><Field label="Estimated maintenance calories" value={maintenance} onChange={setMaintenance} numeric/><Button label="Calculate approximate targets" onPress={()=>void run(async()=>setNutrition(await api('/nutrition/target','POST',{weight_kg:Number(weight),maintenance_estimate:Number(maintenance),adjustment:0,meals:4,allergies:[]})))}/>{nutrition&&<Text style={s.text}>{nutrition.calories_estimate} kcal · protein {nutrition.protein_g}g · fat {nutrition.fat_g}g · carbohydrate {nutrition.carbohydrate_g}g</Text>}</View>
 <Text style={s.muted}>Camera and wearables are not enabled. No camera or microphone permission is requested.</Text><Button secondary label="Sign out & erase device cache" onPress={()=>Alert.alert('Sign out?','Pending unsynced logs will be erased.',[{text:'Cancel',style:'cancel'},{text:'Sign out',onPress:()=>void run(async()=>{await api('/auth/logout','POST');await store.clear();setSession(false);setProfile(null);setWorkout(null);setNewKey('');setLogged({});setOutbox([]);})}])}/></>}
 </>}
 <Text style={s.footer}>ASSESS / TRAIN / RECOVER / ADAPT{'\n'}Development build · training policy requires professional review</Text></ScrollView></SafeAreaView></SafeAreaProvider>;
}
function SetEntry({number,item,done,save}:{number:number;item:any;done:boolean;save:(r:string,l:string,e:string,p:boolean,s:boolean)=>void}){const[r,setR]=useState(String(item.reps)),[l,setL]=useState(String(item.load_kg??0)),[e,setE]=useState(String(item.rpe)),[pain,setPain]=useState(false);return <View style={s.set}>{done?<Text style={s.muted}>Set {number} saved</Text>:<><Text style={s.label}>SET {number} · enter actual performance</Text><Field label="Completed reps" value={r} onChange={setR} numeric/><Field label="Actual load kg · 0 for bodyweight" value={l} onChange={setL} numeric/><Field label="Actual RPE · 1 to 10" value={e} onChange={setE} numeric/><View style={s.row}><Text style={s.text}>Pain in this set?</Text><Switch accessibilityLabel="Pain in this set" value={pain} onValueChange={setPain}/></View><Button label={'Save set '+number} onPress={()=>save(r,l,e,pain,false)}/><Button secondary label={'Skip set '+number} onPress={()=>save('0','0',e,pain,true)}/></>}</View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.bg},content:{padding:24,paddingBottom:60,gap:16,maxWidth:760,width:'100%',alignSelf:'center'},brand:{flexDirection:'row',alignItems:'center',gap:16,marginBottom:18},logo:{color:colors.lime,fontSize:24,fontWeight:'900'},eyebrow:{color:colors.lime,fontSize:12,fontWeight:'700',letterSpacing:1.6},title:{fontSize:40,lineHeight:45,color:colors.text,fontWeight:'700',letterSpacing:-1.4},muted:{color:colors.muted,fontSize:15,lineHeight:23},text:{color:colors.text,fontSize:16,lineHeight:25},card:{backgroundColor:colors.card,borderRadius:24,padding:22,gap:16,borderWidth:1,borderColor:colors.line},heading:{fontSize:23,lineHeight:29,fontWeight:'600',color:colors.text},label:{fontSize:13,color:colors.muted,marginBottom:8},input:{minHeight:50,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,color:colors.text,fontSize:17,backgroundColor:colors.bg},button:{minHeight:52,justifyContent:'center',alignItems:'center',backgroundColor:colors.lime,borderRadius:14,padding:14},secondary:{backgroundColor:colors.card,borderWidth:1,borderColor:colors.line},buttonText:{color:colors.bg,fontSize:16,fontWeight:'700',textAlign:'center'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},tabs:{flexDirection:'row',flexWrap:'wrap',gap:6,marginBottom:18},tab:{minHeight:48,padding:12,borderRadius:12,justifyContent:'center'},activeTab:{backgroundColor:colors.lime},tabText:{color:colors.muted,fontWeight:'600',fontSize:14},status:{color:colors.lime,fontSize:14,lineHeight:22},exercise:{gap:14,paddingVertical:18,borderTopWidth:1,borderTopColor:colors.line},set:{gap:12,padding:14,borderRadius:16,backgroundColor:colors.bg},heroNumber:{fontSize:54,fontWeight:'700',color:colors.lime},footer:{color:colors.muted,fontSize:11,lineHeight:19,letterSpacing:1,marginTop:30}});
